package practice;

public class Main {

	public static void main(String[] args) throws Exception{
		boolean isErr = true;
		if(isErr) {
			System.out.println("データが壊れています。異常終了します");
			System.exit(1);
		}
		System.out.println("正常終了しました");
	}
}
	
